Revert "tools: doxygen: enable WARN_AS_ERROR"
This reverts commit 1a97b40088b7669280b4414d3c1a30fa44d96ec0.

Fix following warning:
error: The selected output language "chinese" has not been updated
since release 1.8.15.  As a result some sentences may appear in English.

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I2e8bf96670f04c1e62fe5d45b27ea51237f2a067